FROM alpine AS uentry-installer
RUN set -eux; \
	arch="$(uname -m)"; \
	case "$arch" in \
		x86_64|amd64) release_arch="x86_64" ;; \
		aarch64|arm64) release_arch="aarch64" ;; \
		*) echo "Unsupported architecture: $arch" >&2; exit 1 ;; \
	esac; \
	mkdir -p /usr/local/bin; \
	wget -qO- "https://github.com/ysginc/uentry/releases/download/latest/uentry-${release_arch}-musl.tar.gz" | tar -xz -C /usr/local/bin uentry

FROM prom/prometheus:v2.55.1
COPY --from=uentry-installer /usr/local/bin/uentry /uentry
COPY uentry.vuln.yaml /etc/uentry/config.yaml
USER root
RUN chmod +x /uentry && mkdir -p /etc/uentry
USER nobody
ENTRYPOINT ["/uentry"]
CMD ["prometheus", "--version"]
