FROM python:3.12-alpine
COPY uentry /uentry
COPY uentry.secure.yaml /etc/uentry/config.yaml
RUN chmod +x /uentry && mkdir -p /etc/uentry /tmp
ENTRYPOINT ["/uentry", "--strict"]
CMD ["python", "--version"]
